version: '3.4'
services:
  disco-registry:
    image: open-disco-newman
    ports:
      - "8282:8282"
    command: []

  newman:
    image: postman/newman
    command: sh -c 'while sleep 3600; do :; done'
    entrypoint: ""
    links:
      - disco-registry
